server:
  port: 8086
spring:
  application:
    name: resource-processor
  rabbitmq:
    retry:
      count: 2
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      create: Resources.Create
      create_dead: Resources.Create.Dead
      delete: Resources.Delete
      delete_dead: Resources.Delete.Dead

resource-service:
  name: resource-service
song-service:
  name: song-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true